# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (6)
# #########################################################################

class Assertion(BaseModel):
    target: typing.Optional[str] = Field(default=None, description='The rubric slug this claim pertains to. Must be one of the scoring dimension slugs, constraint slugs, or \'non_scoring:obtainability\'. See the rubric text for the complete closed vocabulary.')
    fit: typing.Optional[str] = Field(default=None, description='Poor, Mixed, or Strong — the claim\'s polarity in rubric vocabulary. Do not emit numeric scores.')
    provenance: typing.Optional[str] = Field(default=None, description='Always \'model_proposed\' for assertions produced by this function.')
    chunk: typing.Optional[str] = Field(default=None, description='The verbatim span from the page content that grounded this claim. Must be non-empty.')
    citations: typing.List["Citation"] = Field(description='One or more citations. Always non-empty. For a job posting the URL is the posting URL and the quote is the span supporting the claim.')
    created_at: typing.Optional[str] = Field(default=None, description='ISO 8601 UTC timestamp of extraction, e.g. \'2026-08-26T12:00:00Z\'.')

class Citation(BaseModel):
    url: typing.Optional[str] = Field(default=None, description='The URL of the source page where this claim was found.')
    quote: typing.Optional[str] = Field(default=None, description='The verbatim span from the source that supports this claim. Must be present and non-empty.')
    host: typing.Optional[str] = Field(default=None, description='The domain serving the content, e.g. \'linkedin.com\' or \'acme.com\'.')
    source_provenance: typing.Optional[str] = Field(default=None, description='Whether this host is the originating source or an aggregator mirror, e.g. \'official\', \'aggregator\', \'news\'.')
    independent: typing.Optional[bool] = Field(default=None, description='True if this citation is corroborating evidence from an independent source; false if it is the same underlying claim re-published.')
    source_date: typing.Optional[str] = Field(default=None, description='ISO date (YYYY-MM-DD) when the claim was observed, if available. Null if unknown.')

class FetchAction(BaseModel):
    tag: typing.Optional[str] = Field(default=None, description='Always \'fetch\'.')
    url: typing.Optional[str] = Field(default=None, description='The URL to fetch. Must be non-empty.')

class IdentificationResult(BaseModel):
    company_name: typing.Optional[str] = Field(default=None, description='The legal or commonly-known company name. Should not include department or product name.')
    opening_title: typing.Optional[str] = Field(default=None, description='The title of the role as it would appear to applicants (e.g., \'Staff Engineer\' or \'Platform Lead\').')
    opening_notes: typing.Optional[str] = Field(default=None, description='Free-text summary the LLM uses to distinguish openings when more than one is in scope. Not surfaced as a user-visible field.')

class SearchAction(BaseModel):
    tag: typing.Optional[str] = Field(default=None, description='Always \'search\'.')
    query: typing.Optional[str] = Field(default=None, description='The search query to issue. Must be non-empty.')

class StopAction(BaseModel):
    tag: typing.Optional[str] = Field(default=None, description='Always \'stop\'.')
    reason: typing.Optional[str] = Field(default=None, description='One sentence: why the pass is stopping. Must be non-empty.')

# #########################################################################
# Generated type aliases (1)
# #########################################################################


Action: typing_extensions.TypeAlias = typing.Optional[typing.Union["StopAction", "FetchAction", "SearchAction"]]


# #########################################################################
# Model rebuilds (6)
# #########################################################################
# Resolve string forward references now that every model above is defined so
# class declaration order never breaks Pydantic construction (issue #793).
# Recursive models are intentionally omitted (Pydantic resolves those lazily;
# eagerly rebuilding them can recurse).
Assertion.model_rebuild()
Citation.model_rebuild()
FetchAction.model_rebuild()
IdentificationResult.model_rebuild()
SearchAction.model_rebuild()
StopAction.model_rebuild()
