# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def DecidePlan(self, opening_id: str,company_name: str,opening_title: str,rubric_text: str,targets_covered: str,searches_used: int,search_budget: int,tokens_used: int,token_budget: int,last_context_text: str,coverage_summary: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List[typing.Union["types.StopAction", "types.FetchAction", "types.SearchAction"]]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.DecidePlan(opening_id=opening_id,company_name=company_name,opening_title=opening_title,rubric_text=rubric_text,targets_covered=targets_covered,searches_used=searches_used,search_budget=search_budget,tokens_used=tokens_used,token_budget=token_budget,last_context_text=last_context_text,coverage_summary=coverage_summary,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="DecidePlan", args={
                "opening_id": opening_id,"company_name": company_name,"opening_title": opening_title,"rubric_text": rubric_text,"targets_covered": targets_covered,"searches_used": searches_used,"search_budget": search_budget,"tokens_used": tokens_used,"token_budget": token_budget,"last_context_text": last_context_text,"coverage_summary": coverage_summary,
            })
            return typing.cast(typing.List[typing.Union["types.StopAction", "types.FetchAction", "types.SearchAction"]], __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractAssertions(self, chunk: str,rubric_text: str,existing_assertions: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.Assertion"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractAssertions(chunk=chunk,rubric_text=rubric_text,existing_assertions=existing_assertions,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractAssertions", args={
                "chunk": chunk,"rubric_text": rubric_text,"existing_assertions": existing_assertions,
            })
            return typing.cast(typing.List["types.Assertion"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    def IdentifyOpening(self, page_content: str,
        baml_options: BamlCallOptions = {},
    ) -> types.IdentificationResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.IdentifyOpening(page_content=page_content,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="IdentifyOpening", args={
                "page_content": page_content,
            })
            return typing.cast(types.IdentificationResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DecidePlan(self, opening_id: str,company_name: str,opening_title: str,rubric_text: str,targets_covered: str,searches_used: int,search_budget: int,tokens_used: int,token_budget: int,last_context_text: str,coverage_summary: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List[typing.Union["stream_types.StopAction", "stream_types.FetchAction", "stream_types.SearchAction"]], typing.List[typing.Union["types.StopAction", "types.FetchAction", "types.SearchAction"]]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="DecidePlan", args={
            "opening_id": opening_id,"company_name": company_name,"opening_title": opening_title,"rubric_text": rubric_text,"targets_covered": targets_covered,"searches_used": searches_used,"search_budget": search_budget,"tokens_used": tokens_used,"token_budget": token_budget,"last_context_text": last_context_text,"coverage_summary": coverage_summary,
        })
        return baml_py.BamlSyncStream[typing.List[typing.Union["stream_types.StopAction", "stream_types.FetchAction", "stream_types.SearchAction"]], typing.List[typing.Union["types.StopAction", "types.FetchAction", "types.SearchAction"]]](
          __result__,
          lambda x: typing.cast(typing.List[typing.Union["stream_types.StopAction", "stream_types.FetchAction", "stream_types.SearchAction"]], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List[typing.Union["types.StopAction", "types.FetchAction", "types.SearchAction"]], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractAssertions(self, chunk: str,rubric_text: str,existing_assertions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.Assertion"], typing.List["types.Assertion"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractAssertions", args={
            "chunk": chunk,"rubric_text": rubric_text,"existing_assertions": existing_assertions,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.Assertion"], typing.List["types.Assertion"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.Assertion"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.Assertion"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def IdentifyOpening(self, page_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.IdentificationResult, types.IdentificationResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="IdentifyOpening", args={
            "page_content": page_content,
        })
        return baml_py.BamlSyncStream[stream_types.IdentificationResult, types.IdentificationResult](
          __result__,
          lambda x: typing.cast(stream_types.IdentificationResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.IdentificationResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DecidePlan(self, opening_id: str,company_name: str,opening_title: str,rubric_text: str,targets_covered: str,searches_used: int,search_budget: int,tokens_used: int,token_budget: int,last_context_text: str,coverage_summary: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DecidePlan", args={
            "opening_id": opening_id,"company_name": company_name,"opening_title": opening_title,"rubric_text": rubric_text,"targets_covered": targets_covered,"searches_used": searches_used,"search_budget": search_budget,"tokens_used": tokens_used,"token_budget": token_budget,"last_context_text": last_context_text,"coverage_summary": coverage_summary,
        }, mode="request")
        return __result__
    def ExtractAssertions(self, chunk: str,rubric_text: str,existing_assertions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractAssertions", args={
            "chunk": chunk,"rubric_text": rubric_text,"existing_assertions": existing_assertions,
        }, mode="request")
        return __result__
    def IdentifyOpening(self, page_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="IdentifyOpening", args={
            "page_content": page_content,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DecidePlan(self, opening_id: str,company_name: str,opening_title: str,rubric_text: str,targets_covered: str,searches_used: int,search_budget: int,tokens_used: int,token_budget: int,last_context_text: str,coverage_summary: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DecidePlan", args={
            "opening_id": opening_id,"company_name": company_name,"opening_title": opening_title,"rubric_text": rubric_text,"targets_covered": targets_covered,"searches_used": searches_used,"search_budget": search_budget,"tokens_used": tokens_used,"token_budget": token_budget,"last_context_text": last_context_text,"coverage_summary": coverage_summary,
        }, mode="stream")
        return __result__
    def ExtractAssertions(self, chunk: str,rubric_text: str,existing_assertions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractAssertions", args={
            "chunk": chunk,"rubric_text": rubric_text,"existing_assertions": existing_assertions,
        }, mode="stream")
        return __result__
    def IdentifyOpening(self, page_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="IdentifyOpening", args={
            "page_content": page_content,
        }, mode="stream")
        return __result__
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))