# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (6)
# #########################################################################

class Assertion(BaseModel):
    target: str = Field(description='The rubric slug this claim pertains to. Must be one of the scoring dimension slugs, constraint slugs, or \'non_scoring:obtainability\'. See the rubric text for the complete closed vocabulary.')
    fit: str = Field(description='Poor, Mixed, or Strong — the claim\'s polarity in rubric vocabulary. Do not emit numeric scores.')
    provenance: str = Field(description='Always \'model_proposed\' for assertions produced by this function.')
    chunk: str = Field(description='The verbatim span from the page content that grounded this claim. Must be non-empty.')
    citations: typing.List["Citation"] = Field(description='One or more citations. Always non-empty. For a job posting the URL is the posting URL and the quote is the span supporting the claim.')
    created_at: str = Field(description='ISO 8601 UTC timestamp of extraction, e.g. \'2026-08-26T12:00:00Z\'.')

class Citation(BaseModel):
    url: str = Field(description='The URL of the source page where this claim was found.')
    quote: str = Field(description='The verbatim span from the source that supports this claim. Must be present and non-empty.')
    host: str = Field(description='The domain serving the content, e.g. \'linkedin.com\' or \'acme.com\'.')
    source_provenance: str = Field(description='Whether this host is the originating source or an aggregator mirror, e.g. \'official\', \'aggregator\', \'news\'.')
    independent: bool = Field(description='True if this citation is corroborating evidence from an independent source; false if it is the same underlying claim re-published.')
    source_date: typing.Optional[str] = Field(default=None, description='ISO date (YYYY-MM-DD) when the claim was observed, if available. Null if unknown.')

class FetchAction(BaseModel):
    tag: str = Field(description='Always \'fetch\'.')
    url: str = Field(description='The URL to fetch. Must be non-empty.')

class IdentificationResult(BaseModel):
    company_name: str = Field(description='The legal or commonly-known company name. Should not include department or product name.')
    opening_title: str = Field(description='The title of the role as it would appear to applicants (e.g., \'Staff Engineer\' or \'Applied AI Lead\').')
    opening_notes: str = Field(description='Free-text summary the LLM uses to distinguish openings when more than one is in scope. Not persisted as a user-visible field at slice 2.')

class SearchAction(BaseModel):
    tag: str = Field(description='Always \'search\'.')
    query: str = Field(description='The search query to issue. Must be non-empty.')

class StopAction(BaseModel):
    tag: str = Field(description='Always \'stop\'.')
    reason: str = Field(description='One sentence: why the pass is stopping. Must be non-empty.')

# #########################################################################
# Generated type aliases (1)
# #########################################################################


Action: typing_extensions.TypeAlias = typing.Union["StopAction", "FetchAction", "SearchAction"]


# #########################################################################
# Model rebuilds (6)
# #########################################################################
# Resolve string forward references now that every model above is defined so
# class declaration order never breaks Pydantic construction (issue #793).
# Recursive models are intentionally omitted (Pydantic resolves those lazily;
# eagerly rebuilding them can recurse).
Assertion.model_rebuild()
Citation.model_rebuild()
FetchAction.model_rebuild()
IdentificationResult.model_rebuild()
SearchAction.model_rebuild()
StopAction.model_rebuild()
