# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Assertion": types.Assertion,
    "stream_types.Assertion": stream_types.Assertion,

    "types.Citation": types.Citation,
    "stream_types.Citation": stream_types.Citation,

    "types.FetchAction": types.FetchAction,
    "stream_types.FetchAction": stream_types.FetchAction,

    "types.IdentificationResult": types.IdentificationResult,
    "stream_types.IdentificationResult": stream_types.IdentificationResult,

    "types.SearchAction": types.SearchAction,
    "stream_types.SearchAction": stream_types.SearchAction,

    "types.StopAction": types.StopAction,
    "stream_types.StopAction": stream_types.StopAction,


}